-- Automotive Manufacturers (65+)
INSERT INTO public.manufacturers (name, slug, type, country) VALUES
('Acura', 'acura', 'automotive', 'Japan'),
('Alfa Romeo', 'alfa-romeo', 'automotive', 'Italy'),
('Audi', 'audi', 'automotive', 'Germany'),
('BMW', 'bmw', 'automotive', 'Germany'),
('Buick', 'buick', 'automotive', 'USA'),
('Cadillac', 'cadillac', 'automotive', 'USA'),
('Chevrolet', 'chevrolet', 'automotive', 'USA'),
('Chrysler', 'chrysler', 'automotive', 'USA'),
('Dodge', 'dodge', 'automotive', 'USA'),
('Fiat', 'fiat', 'automotive', 'Italy'),
('Ford', 'ford', 'automotive', 'USA'),
('Genesis', 'genesis', 'automotive', 'South Korea'),
('GMC', 'gmc', 'automotive', 'USA'),
('Honda', 'honda', 'automotive', 'Japan'),
('Hyundai', 'hyundai', 'automotive', 'South Korea'),
('Infiniti', 'infiniti', 'automotive', 'Japan'),
('Jaguar', 'jaguar', 'automotive', 'UK'),
('Jeep', 'jeep', 'automotive', 'USA'),
('Kia', 'kia', 'automotive', 'South Korea'),
('Land Rover', 'land-rover', 'automotive', 'UK'),
('Lexus', 'lexus', 'automotive', 'Japan'),
('Lincoln', 'lincoln', 'automotive', 'USA'),
('Mazda', 'mazda', 'automotive', 'Japan'),
('Mercedes-Benz', 'mercedes-benz', 'automotive', 'Germany'),
('Mercury', 'mercury', 'automotive', 'USA'),
('Mini', 'mini', 'automotive', 'UK'),
('Mitsubishi', 'mitsubishi', 'automotive', 'Japan'),
('Nissan', 'nissan', 'automotive', 'Japan'),
('Oldsmobile', 'oldsmobile', 'automotive', 'USA'),
('Pontiac', 'pontiac', 'automotive', 'USA'),
('Porsche', 'porsche', 'automotive', 'Germany'),
('Ram', 'ram', 'automotive', 'USA'),
('Saab', 'saab', 'automotive', 'Sweden'),
('Saturn', 'saturn', 'automotive', 'USA'),
('Scion', 'scion', 'automotive', 'Japan'),
('Subaru', 'subaru', 'automotive', 'Japan'),
('Suzuki', 'suzuki', 'automotive', 'Japan'),
('Tesla', 'tesla', 'automotive', 'USA'),
('Toyota', 'toyota', 'automotive', 'Japan'),
('Volkswagen', 'volkswagen', 'automotive', 'Germany'),
('Volvo', 'volvo', 'automotive', 'Sweden'),
('Isuzu', 'isuzu', 'automotive', 'Japan'),
('Hummer', 'hummer', 'automotive', 'USA'),
('Daewoo', 'daewoo', 'automotive', 'South Korea'),
('Geo', 'geo', 'automotive', 'USA'),
('Eagle', 'eagle', 'automotive', 'USA'),
('Plymouth', 'plymouth', 'automotive', 'USA'),
('Rivian', 'rivian', 'automotive', 'USA'),
('Lucid', 'lucid', 'automotive', 'USA'),
('Polestar', 'polestar', 'automotive', 'Sweden'),
('Maserati', 'maserati', 'automotive', 'Italy'),
('Bentley', 'bentley', 'automotive', 'UK'),
('Rolls-Royce', 'rolls-royce', 'automotive', 'UK'),
('Aston Martin', 'aston-martin', 'automotive', 'UK'),
('Ferrari', 'ferrari', 'automotive', 'Italy'),
('Lamborghini', 'lamborghini', 'automotive', 'Italy'),
('McLaren', 'mclaren', 'automotive', 'UK'),
('Lotus', 'lotus', 'automotive', 'UK'),
('Maybach', 'maybach', 'automotive', 'Germany'),
('Smart', 'smart', 'automotive', 'Germany'),
('Freightliner', 'freightliner', 'automotive', 'USA'),
('Kenworth', 'kenworth', 'automotive', 'USA'),
('Peterbilt', 'peterbilt', 'automotive', 'USA'),
('International', 'international', 'automotive', 'USA'),
('Mack', 'mack', 'automotive', 'USA')
ON CONFLICT (slug) DO NOTHING;

-- Residential Lock Manufacturers (11+)
INSERT INTO public.manufacturers (name, slug, type, country) VALUES
('Schlage', 'schlage', 'residential', 'USA'),
('Kwikset', 'kwikset', 'residential', 'USA'),
('Yale', 'yale', 'residential', 'USA'),
('Defiant', 'defiant', 'residential', 'USA'),
('Baldwin', 'baldwin', 'residential', 'USA'),
('Medeco', 'medeco', 'residential', 'USA'),
('Mul-T-Lock', 'mul-t-lock', 'residential', 'Israel'),
('ASSA', 'assa', 'residential', 'Sweden'),
('Sargent', 'sargent', 'residential', 'USA'),
('Corbin Russwin', 'corbin-russwin', 'residential', 'USA'),
('Emtek', 'emtek', 'residential', 'USA'),
('Weiser', 'weiser', 'residential', 'Canada'),
('Brinks', 'brinks', 'residential', 'USA')
ON CONFLICT (slug) DO NOTHING;
